### ISSUE TITLE
Pass an ActionRegistry on instantiation

### ISSUE THREAD

**Issue by kitsonk** [dojo/app#11]
**Version and Environment:**

Dojo2 version: master

Environment(s): IE10 / IE11 / Edge / Chrome / Firefox / Safari / iOS / Android / Node.js

**Proposal**

We should consider adding support for the app factory to pass a reference to the action registry to instances in support of dojo/widgets#14.  This would enable widget mixins to be able to resolve actions based on their ID.

**Comment by novemberborn** [comment]
We should abstract this issue:

---

The factory should pass action, store and widget registry references as options to widget factories. This will support dojo/widgets#14 and related features, enabling widget mixins to resolve actions, stores and widgets based on their ID.

The registry interface should be compatible with:

```typescript
interface Registry<Item> {
	get<Item>(id: string): Promise<Item>;
	identify(value: Item): string;
}
```

This base interface should probably be declared in `dojo-widgets`

**Comment by kitsonk** [comment]
Don't forget, structural typing... so I don't think we need to bridge across package boundries, this is simply the "structure" that someone would expect...  There could be other methods, but those two are what are needed to be consumed.

Another thought is that we could further simply this into a registry provider interfaces, so that we don't have to decide *now* what classes of objects would be supported by a registry.  A registry for registries so to speak.  Something like:

```typescript
interface IdentityRegistry<T> {
    get(id: string): Promise<T>;
    identify(value: T): string;
}

interface RegistryProvider {
    get(type: 'stores'): IdentityRegistry<Store>;
    get(type: 'widgets'): IdentityRegistry<Renderable>;
    get(type: 'actions'): IdentityRegistry<Actionable>;
    get(type: string): Registry<any>;
}
```

**Comment by novemberborn** [comment]
`RegistryProvider` seems sensible. enough. Less unpacking and repacking of `options`, that's for sure.

`IdentityRegistry` is funny,  `dojo-app` already has one (#7). Though I imagine we only want to hand out a read-only registry.

This is blocked by #14 which introduces the necessary changes to pass options to all the widget factories.
