### ISSUE TITLE
Call configure method for action instance on registration with app

### ISSUE THREAD

**Issue by agubler** [dojo/app#19]
Currently the `configure` method of an action is only called on first use, this makes sense when the `app` is passed `factory` on `action` registration but if `app` is passed an action instance it should call the `configure` method on registration.

**Comment by novemberborn** [comment]
@agubler should this also happening when you load an action definition that has an actual `instance` reference (not a module ID)? I'm leaning towards definitions always being lazy, also as far as #11 is concerned. (You won't be able to identify a instance definition unless you call `getAction()` first.)

**Comment by novemberborn** [comment]
I'm thinking of reverting this to the previous behavior. Action instances are now the only things that get synchronous access to the registry, and can thus cause stores etc to be resolved. This is problematic if the instance is loaded before the store is registered, e.g. with `app-actions` from #33.

**Comment by novemberborn** [comment]
Ah turns out that the `app-actions` implementation ends up with a factory that returns the instance, so those are not configured synchronously. Still, it's weird that just `registerAction()` behaves this way.
