### ISSUE TITLE
Default store not registered on app creation.

### ISSUE THREAD

**Issue by agubler** [dojo/app#27]
When a default store is passed to on app creation `createApp({ defaultStore: myStore });` it should be registered so that it can be retrieved from the registry, such as:

```js
registry.getStore('defaultStore').then((myStore: <any>) => {
	myClass.myStore = myStore;
});
```

Currently in order to reference the default store it has to be explicitly registered after app creation `app.registerStore('myStore', myStore);`

**Comment by novemberborn** [comment]
Perhaps we can register it under a symbol?

**Comment by agubler** [comment]
I don't see why not as long as it can be retrieved from the registry.

**Comment by kitsonk** [comment]
Just remember to place the symbol somewhere consistent.
