### ISSUE TITLE
Providing initial state as part of a application description

### ISSUE THREAD

**Issue by kitsonk** [dojo/app#29]
# Enhancement

Currently, bootstrapping an application requires a two-step process of creating the widget state in a widget store and then describing the application.  We could benefit from allowing the application `loadDefinition` to automatically populate initial state of a widget/action to the appropriate store.  For example instead of this:

```typescript
import createMemoryStore from 'dojo-widgets/util/createMemoryStore';
import createButton from 'dojo-widgets/createButton';
import createWidget from 'dojo-widgets/createWidget';
import createAction from 'dojo-actions/createAction';
import createApp from 'dojo-app/createApp';

const widgetStore = createMemoryStore({
	data: [
		{ id: 'widget1', classes: [ 'pad-1em' ] },
		{ id: 'widget2', label: 'Widget 2', listeners: { click: 'actionClick' } }
	]
});

const app = createApp({ defaultStore: widgetStore });

app.registerAction('actionClick', createAction({
	do() {
		alert('I was clicked!');
	}
});

app.loadDefinition({
	widgets: [
		{ id: 'widget1', factory: createWidget },
		{ id: 'widget2', factory: createButton }
	]
});
```

Where as we could do something like this:

```typescript
import createMemoryStore from 'dojo-widgets/util/createMemoryStore';
import createButton from 'dojo-widgets/createButton';
import createWidget from 'dojo-widgets/createWidget';
import createAction from 'dojo-actions/createAction';
import createApp from 'dojo-app/createApp';

const app = createApp({ defaultStore: createMemoryStore() });

app.registerAction('actionClick', createAction({
	do() {
		alert('I was clicked!');
	}
});

app.loadDefinition({
	widgets: [
		{ id: 'widget1', factory: createWidget, state: { classes: [ 'pad-1em' ] } },
		{ id: 'widget2', factory: createButton, state: { listeners: { click: 'actionClick' } } }
	]
});
```

**Comment by novemberborn** [comment]
Same for `registerWidgetFactory`.

**Comment by kitsonk** [comment]
One thought that came up was that if the widget state was in a persistent store, indiscriminately overwriting the widget state would be a bad thing.  So instead of `patch()` we should consider using `add()` ignoring any rejects.

**Comment by novemberborn** [comment]
This would be the equivalent of `data-state` on custom elements, so that makes sense.

Regarding `add()`, should I change the custom element behavior as well?

> Custom elements that have widget IDs and a stateFrom store may set their data-state attribute to an initial state object, encoded as a JSON string. The store will be patched with the initial state and the widget ID before the widget is created.

**Comment by kitsonk** [comment]
Relates to #33.  I will comment more specifically later this week.
