### ISSUE TITLE
Consider dropping data- prefixes for custom element attributes

### ISSUE THREAD

**Issue by novemberborn** [dojo/app#48]
Currently we require non-standard attributes on custom elements to be prefixed with `data-`. This seems silly, since the elements themselves are non-standard already. We should consider dropping this requirement.

Of course the `is` attribute allows a standard element to behave as if it was a custom element. In this case the attributes should be prefixed.

Our choices are:

1. Be consistent and *always* require `data-` prefixes
2. Be consistent and *never* require `data-` prefixes
3. Support attributes with and without prefixes (with a defined priority and/or warnings)
4. Only require `data-` prefixes in combination with correct uses of the `is` attribute (the attribute is ignored when used on a custom element), otherwise ignore attributes with `data-` prefixes

The first choice is how app behaves currently. The second choice seems problematic when applied to standard elements. The third choice is confusing.

For the fourth choice it could be argued that once a user opts for the `is` approach they already know they're using standard elements and that therefore the attributes need to be prefixed.

I'm in favor of the fourth choice, but it largely hinges on the expected usage patterns. If we think most users would use custom elements then not requiring `data-` prefixes would provide a better experience.

**Comment by dylans** [comment]
My pro for choice 4 is that the use of `data-` is only really applicable for blocks of markup that should be run through the HTML5 validator. What does the validator do with custom elements currently, if anything?

The con for choice 4 is that a lack of consistency if someone copies markup from a custom element to create a standard element. I would be ok with choice 4 if there's an obvious debugging/warning/error mechanism when an attribute is being ignored. If not, I would probably err on the side of either choice 1 (consistency) or choice 3 (just works for an end user).

**Comment by novemberborn** [comment]
@dojo/dojo-2-committers thoughts?

**Comment by kitsonk** [comment]
My 2p, which is totally just an opinion... 💯 on consistency. Therefore I would lean more towards `data-` which also helps denote that it isn't a direct concern of the HTML rendering engine, but someone else.

**Comment by Tomdye** [comment]
I would agree with the use of `data-` or `dojo-` in order to be consistent throughout. Makes for a clear separation of concerns as well.

**Comment by kitsonk** [comment]
Let's go with Option 1  *always* use `data-` for attributes parsed by `app`.  All other attributes are *ignored* by `app` even if they are *valid* HTML attributes.
