### ISSUE TITLE
Factory registration for dynamic children

### ISSUE THREAD

**Issue by agubler** [dojo/app#54]
**Proposal:** API to support creation of widgets based on `type` defined as part of the widget state stored in a registered widget store, similar to how custom widgets work for the bootstrap markup.

*In fact custom widgets could even be leveraged to achieve this functionality*

Register factories with app for dynamically creating and registering widgets.

```js
app.registerFactory('item', createItem);
```
```js
app.registerFactories([
  {
    id: 'item',
    factory: createItem
  }
]);
```

Potential create APIs on the app widget registry:

```js
registry.create(type, state) {
  // look up id in widget registry
  // throw if exists
  // look up type in factory registry
  // throw if factory not found
  // create widget, return promise
};
```
```js
create('item', {'id': 'item-1'});
```

or 

```js
registry.create(id) {
  // look up id in widget registry
  // throw if exists
  // look up entry in widget store
  // throw if not exists
  // look up type in factory registry
  // throw if factory not found
  // create widget, return promise
};
```
```js
create('item-1');
```

This would help to resolve complexities dynamically adding widgets to a parent by simply adding the widget state record (with a type that matches a registered factory) and then adding the child `id` to the children array of the parent (with the `createStatefulChildrenMixin` dealing with the call to the registry)

**Comment by kitsonk** [comment]
I agree this would be useful.

Is it worth considering the `type` resolution logic, which IIRC is used elsewhere, where if the `type` is not registered, it can be attempted to be treated as a MID, which `app` will attempt to load?

```javascript
{
    id: 'item',
    type: '/app/widgets/createCustomWidget',
    options: {}
}
```

I know this might raise questions about bundling/build optimisation, but I think we would be able to provide tooling which collects any MIDs used in an application with `app` and ensure those get into the build specification for the application.
