### ISSUE TITLE
Utilise dojo-core/load for dynamic loading of modules

### ISSUE THREAD

**Issue by kitsonk** [dojo/app#68]
**Enhancement**

We should consider using `dojo-core/load` to dynamically load modules, which hopefully we can continue to abstract away any logic that would become problematic when using a non-AMD loader and any dynamic loading features of `app`.

This would result in us contracting that `load` would be able to continue to load certain resources that are then loaded into a particular context (e.g. executable code) and `dojo-core/request` would focus on retrieving resources which are generally not executed/evaluated (e.g. CSS, HTML, etc...)

**Comment by agubler** [comment]
Closing for the same reason as stated on PR https://github.com/dojo/app/pull/74#issuecomment-276409721
