### ISSUE TITLE
Move IdentityRegistry to core?

### ISSUE THREAD

**Issue by novemberborn** [dojo/app#7]
`IdentityRegistry` is pretty low-level and could be in Core. `dojo-core/Registry` should perhaps be renamed to `dojo-core/MatchRegistry` or similar.

**Comment by kitsonk** [comment]
Yes, I like that idea.

**Comment by novemberborn** [comment]
This is blocked until the core/shim extraction settles down.

**Comment by kitsonk** [comment]
This has been done.

**Comment by novemberborn** [comment]
<https://github.com/dojo/app/pull/61> still needs to land.

**Comment by kitsonk** [comment]
Yes. Sorry.
