### ISSUE TITLE
Support Ctor and proto options?

### ISSUE THREAD

**Issue by novemberborn** [dojo/app#8]
[`parser`](https://github.com/dojo/parser) supports `Ctor` and `proto` options. These likely predate the current focus on factory methods. Should the app factory support them regardless?

**Comment by kitsonk** [comment]
My feeling was that it was a situation where the `parser` was a generic "instantiation engine".  We are already in the situation where the app factory is an opinionated solution about how an app comes together.  So I think given that, it doesn't make sense for it support things that it wouldn't be able to manage effectively after instantiation.

**Comment by novemberborn** [comment]
Agreed.
