### ISSUE TITLE
Race condition with widget creation by type

### ISSUE THREAD

**Issue by agubler** [dojo/app#80]
When `getWidget` is called for an `id` that is dynamically created using the `.type` from the associated to the state entry. If `getWidget` is called again (with the same id) before the widget has actually been factoried and registered then `app` will try and create the widget again. 

This causes a failure when attempting to register the (duplicate) widget as an entry for that `id` already exists in the registry.

**Version and Environment:**

Dojo2 version: latest

**Code**

```ts
import createApp from 'dojo-app/createApp';
import createMemoryStore from 'dojo-stores/createMemoryStore';

import createWidget from 'dojo-widgets/createWidget';
import createPanel from 'dojo-widgets/createPanel';

const widgetStore = createMemoryStore<any>({
	data: [
		{
			id: 'container'
		}
	]
});

const app = createApp({ defaultWidgetStore: widgetStore });

app.loadDefinition({
	widgets: [
		{
			id: 'container',
			factory: createPanel
		}
	],
	customElements: [
		{
			name: 'dynamically-created-child',
			factory: createWidget
		}
	]
});

app.realize(document.body)
	.then(() => {
		const children: string[] = [];
		for (let i = 0; i < 10; i++) {
			const id = `${i}`;
			children.push(id);
			widgetStore
				.put({id, type: 'dynamically-created-child', label: 'This is label number ' + i})
				.patch({id: 'container', children});

		}
	});

```

**Expected behavior:**

Render 10 children items:

```
This is label number 0
This is label number 1
This is label number 2
This is label number 3
This is label number 4
This is label number 5
This is label number 6
This is label number 7
This is label number 8
This is label number 9
```

**Actual behavior:** 

No children render.

**Comment by novemberborn** [comment]
@agubler feel free to assign to me if you want.

**Comment by agubler** [comment]
I was thinking about how to handle this yesterday, would it be plausible to do a second "check" for the widget in the instanceRegistry before doing the register? If is it there destroy the surplus widget and carry on?

**Comment by agubler** [comment]
Or do you think we could keep a state internally that `app` was in the process of creating the widget for that `id` and skip the creation all together?

**Comment by novemberborn** [comment]
> Or do you think we could keep a state internally that app was in the process of creating the widget for that id and skip the creation all together?

That's effectively what the factories do. They register a new factory which returns the same promise.

Conceivably we could register a widget factory for the given `id` once we determine we can create the widget using its `type`. That always takes precedence, so future calls will invoke that factory to get a promise for the widget instance.
