### ISSUE TITLE
Add different views to Todo

### ISSUE THREAD

**Issue by rorticus** [dojo/app#95]

**Comment by rorticus** [comment]
https://github.com/dojo/examples/compare/master...rorticus:issue-95

**Comment by rorticus** [comment]
![image](https://cloud.githubusercontent.com/assets/2008858/21194941/5a3e29b0-c1f7-11e6-8f7e-a8f376db4435.png)

**Comment by dylans** [comment]
https://github.com/dojo/examples/pull/173
